workflows:
  upload-ipa:
    name: Upload IPA

    scripts:
      - name: Download IPA
        script: |
          curl -L -o app.ipa "https://drive.google.com/uc?export=download&id=11N3Po8d4JCsgCWp_ikunFmbKOLJqaOz_"

      - name: Verify file
        script: |
          ls -lah

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
