export const STR = {
  title: "PICKLEBALL",
  subtitle: "El juego más divertido del mundo",
  btnPlay: "¡JUGAR!",
  btnCustomize: "Personalizar jugador",
  labelPlayer: "TÚ",
  labelCPU: "CPU",
  labelScore: "MARCADOR",
  labelColor: "Color de ropa:",
  labelSkin: "Tono de piel:",
  serving: "SAQUE",
  rally: "¡RALLY!",
  point: "¡PUNTO!",
  fault: "FALTA",
  win: "¡GANASTE! 🎉",
  lose: "El CPU gana... 🤖",
  playAgain: "¡Otra vez!",
  ctrlMove: "WASD / Flechas para moverte",
  ctrlHit: "ESPACIO para golpear",
  ctrlHitMobile: "Toca para golpear",
  dink: "¡Dink!",
  smash: "¡SMASH!",
  serve: "Saque al frente",
  scoreToWin: "Primero en 11 pts (diferencia de 2)",
};
